ExpenseTracker/ExpenseTracker.Web/Areas/User/Models/PaymentMethods/CreatePaymentMethodModel.cs
using ExpenseTracker.Framework.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseTracker.Web.Areas.User.Models.PaymentMethods
{
    public class CreatePaymentMethodModel : PaymentMethodBaseModel
    {
        public string Name { get; set; }

        public void Create()
        {
            var paymentMethod = new PaymentMethod { Name = Name };
            _paymentMethodService.Create(paymentMethod);
        }
    }
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Models/PaymentMethods/DeletePaymentMethodModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseTracker.Web.Areas.User.Models.PaymentMethods
{
    public class DeletePaymentMethodModel : PaymentMethodBaseModel
    {
        public int Id { get; set; }

        public string delete(int id)
        {
            var item = _paymentMethodService.GetById(id);
            _paymentMethodService.Remove(item);
            return item.Name;
        }
    }
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Models/PaymentMethods/EditPaymentMethodModel.cs
using AspNetCore;
using ExpenseTracker.Framework.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseTracker.Web.Areas.User.Models.PaymentMethods
{
    public class EditPaymentMethodModel : PaymentMethodBaseModel
    {
        public string Name { get; set; }
        public int Id { get; set; }


        public void Edit()
        {
            var paymentMethod = new PaymentMethod();
            paymentMethod.Id = Id;
            paymentMethod.Name = Name;
            _paymentMethodService.Update(paymentMethod);
        }

        public void Load(int id)
        {
            PaymentMethod paymentMethod = _paymentMethodService.GetById(id);
            Name = paymentMethod.Name;
        }
    }
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Models/PaymentMethods/PaymentMethodBaseModel.cs
using Autofac;
using ExpenseTracker.Framework.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseTracker.Web.Areas.User.Models.PaymentMethods
{
    public class PaymentMethodBaseModel : UserBaseModel
    {
        public IPaymentMethodService _paymentMethodService;

        public PaymentMethodBaseModel(IPaymentMethodService paymentMethodService)
        {
            _paymentMethodService = paymentMethodService;
        }

        public PaymentMethodBaseModel()
        {
            _paymentMethodService = Startup.AutofacContainer.Resolve<IPaymentMethodService>();
        }
    }
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Models/PaymentMethods/PaymentMethodModel.cs
using ExpenseTracker.Framework.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseTracker.Web.Areas.User.Models.PaymentMethods
{
    public class PaymentMethodModel : PaymentMethodBaseModel
    {
        public PaymentMethodModel(IPaymentMethodService paymentMethodService) : base(paymentMethodService) { }
        public PaymentMethodModel() : base() { }

        internal object GetPaymentMethods(DataTablesAjaxRequestModel tableModel)
        {
            var data = _paymentMethodService.GetPaymentMethods(
                tableModel.PageIndex,
                tableModel.PageSize,
                tableModel.SearchText,
                tableModel.GetSortText(new string[] { "Name" }));

            return new
            {
                recordsTotal = data.total,
                recordsFiltered = data.totalFiltered,
                data = (from record in data.records
                        select new string[]
                        {
                                record.Name,
                                record.Id.ToString()
                                
                        }
                    ).ToArray()

            };
        }
    }
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Controllers/PaymentMethodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using ExpenseTracker.Framework.Exceptions;
using ExpenseTracker.Web.Areas.User.Models;
using ExpenseTracker.Web.Areas.User.Models.PaymentMethods;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;
using Serilog.Core;

namespace ExpenseTracker.Web.Areas.User.Controllers
{
    [Area("User")]
    public class PaymentMethodController : Controller
    {
        public readonly ILogger<PaymentMethodController> _logger;
        public readonly IToastNotification _toaster;

        public PaymentMethodController(ILogger<PaymentMethodController> logger, IToastNotification toast)
        {
            _logger = logger;
            _toaster = toast;
        }

        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<PaymentMethodModel>();
            return View(model);
        }

        public IActionResult GetPayMethods()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = Startup.AutofacContainer.Resolve<PaymentMethodModel>();
            var data = model.GetPaymentMethods(tableModel);
            return Json(data);
        }

        public IActionResult Create()
        {
            var model = Startup.AutofacContainer.Resolve<CreatePaymentMethodModel>();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind(nameof(CreatePaymentMethodModel.Name))]CreatePaymentMethodModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new InvalidModelException("The Model Is Invaild.");


                model.Create();
                _toaster.AddSuccessToastMessage($"{model.Name} Created Successfully");
                _logger.LogInformation($"{model.Name} Payment Method Created Successfully");
            }
            catch (Exception e)
            {
                _toaster.AddErrorToastMessage($"{model.Name} Creation Faild");
                _logger.LogInformation($"Faild to Create {model.Name} Payment Method. Exception is: {e}");
            }
            return RedirectToAction("index");
        }


        public IActionResult Edit(int id)
        {
            var model = Startup.AutofacContainer.Resolve<EditPaymentMethodModel>();
            model.Load(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind(nameof(EditPaymentMethodModel.Id), nameof(EditPaymentMethodModel.Name))] EditPaymentMethodModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new InvalidModelException("The Model Is Invaild.");

                model.Edit();
                _toaster.AddSuccessToastMessage($"{model.Name} Updated Successfully");
                _logger.LogInformation($"{model.Name} Payment Method Updated Successfully");
            }
            catch (Exception e)
            {
                _toaster.AddErrorToastMessage($"{model.Name} Update Faild");
                _logger.LogInformation($"Faild to Update {model.Name} Payment Method. Exception is: {e}");
            }
            return RedirectToAction("index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new InvalidModelException("The Model Is Invaild.");

                var model = new DeletePaymentMethodModel();
                var item = model.delete(id);

                _toaster.AddSuccessToastMessage($"{item} Deleted Successfully");
                _logger.LogInformation($"{item} Payment Method Deleted Successfully");
            }
            catch (Exception e)
            {
                _toaster.AddErrorToastMessage($"Delete Faild");
                _logger.LogInformation($"Faild to Delete Payment Method. Exception is: {e}");
            }
            return RedirectToAction("index");
        }
    }
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Views/PaymentMethod/Create.cshtml
@model CreatePaymentMethodModel

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Payment Method</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Add a payment method</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <form asp-area="user" asp-controller="PaymentMethod" asp-action="Create" method="post" class="form-horizontal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Views/PaymentMethod/Edit.cshtml
@model EditPaymentMethodModel

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Update Payment Method</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Update a payment method</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <form asp-area="user" asp-controller="PaymentMethod" asp-action="Edit" method="post" class="form-horizontal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Name" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

ExpenseTracker/ExpenseTracker.Web/Areas/User/Views/PaymentMethod/Index.cshtml
@model PaymentMethodModel

@section PageStyles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Payment Methods</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="paymentMethodTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete?</p>
                <form id="deleteForm" action="/user/paymentmethod/delete" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="deleteId" value="" name="id" />
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section PageScripts
{
    <!-- DataTables -->
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#paymentMethodTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/User/PaymentMethod/GetPayMethods",
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 1,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/user/paymentmethod/edit/${data}'" value='${data}'>
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Edit
                                        </button>
                                        <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </button>`;
                        }
                    }
                ]
            });

            $('#paymentMethodTable').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                //$("#deleteForm").attr("action", "/admin/category/delete/" + id );
                $("#deleteId").val(id);
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}